### ISSUE TITLE
Las uns daraus ein Java/Kotlin game machen.

### ISSUE THREAD

**Issue by AnderWoche** [letsgamedev/Suffragium#1]
Was meint ihr?

**Comment by AnderWoche** [comment]
Ich habe kein plan von Godot einfach LibGdx/LibKTX nehmen.

**Comment by letsgamedev** [comment]
Ich habe kein Plan von LibGdx lass uns einfach Godot nehmen.

**Comment by AnderWoche** [comment]
Ja, was neues lernen ist auch immer wieder gut :D

**Comment by dzatoah** [comment]
Habe auch keinen Plan von Godot xd

**Comment by retrievaaaa** [comment]
Sehr geehrter @AnderWoche,
ich weiß das dies äußerst off-topic ist, jedoch habe ich Sie per Zufall hier wieder angetroffen und wollte fragen wann sie endlich mal wieder streamen.

MfG,
Ihr größter Fan
