### ISSUE TITLE
[Proposal] GDScript Toolkit verwenden

### ISSUE THREAD

**Issue by ckanitz** [letsgamedev/Suffragium#10]
Ja, ich bin Spaß auf Parties...
Einheitliche Code Styles sind wichtig, gerade bei Open Source Projekten mit vielen Contributors.

Daher der Vorschlag [GDScript Toolkit](https://github.com/Scony/godot-gdscript-toolkit) für styles / linting zu verwenden und ggf. auch eine GitHub Action anzulegen, die automatisch bei neuen PRs auf die Styles checked und ggf. den PR automatisch als invalid flagged (bis der Autor eben nachgebessert hat und alles tutti ist)

**Comment by RedstoneMedia** [comment]
Ich finde, der Code sollte einfach nur lesbar sein und jetzt nicht komplett anderen Prinzipen verwenden. Also: Ich fände, man sollte den Codestyle in einer case by case basis beurteilen und nicht irgendwelche restriktiven Linter Regeln hinzufügen.

**Comment by VatrasCell** [comment]
> Ich finde, der Code sollte einfach nur lesbar sein und jetzt nicht komplett anderen Prinzipen verwenden. Also: Ich fände, man sollte den Codestyle in einer case by case basis beurteilen und nicht irgendwelche restriktiven Linter Regeln hinzufügen.

Ich bin auch der Meinung, dass man erstmal anfangen sollte und wenn sich das hier zu was "größerem" entwickelt, kann man immer noch das einführen und rein Refactoring machen.

**Comment by TazorDE** [comment]
Ich stimme zu, einheitliche Code Styles sind essentiell. Linting oder sogar eine GHAction klingen mir sehr sinnvoll.

**Comment by BlobCodes** [comment]
Damit das Projekt für alle lesbar ist würde ich auch einen einheitlichen Code Style einführen.

> Also: Ich fände, man sollte den Codestyle in einer case by case basis beurteilen und nicht irgendwelche restriktiven Linter Regeln hinzufügen.

Der Linter ist ja jetzt nicht extrem restriktiv. Der sorgt dafür, dass du z.B. Elemente in nem Array zusätzlich zu einem Komma noch mit einem Leerzeichen voneinander Trennen musst.
Dazu gibt's in dem Toolkit nen' formatter, den Code zu formatten ist damit nur ein `gdformat ./*` vor dem `git commit`.

Den Code case-by-case zu beurteilen schafft nur extra Arbeit.

**Comment by RedstoneMedia** [comment]
Man könnte ja erstmal schauen, ob das überhaupt so relevant ist. Wenn der code dann wirklich schrecklich aussieht, kann man das ja immer noch einführen. Weil es wäre jetzt erstmal Arbeit, die nicht hilft mit dem Spiel anzufangen. Es ist zudem sehr schwer sich auf einen einheitlichen Code style zu einigen, weil jeder einen anderen Code style hat.

**Comment by techel** [comment]
Man kann sich ja trotzdem an die [GDScript-Stilrichtlinien](https://docs.godotengine.org/de/stable/tutorials/scripting/gdscript/gdscript_styleguide.html) halten.

**Comment by Joshix-1** [comment]
> Man könnte ja erstmal schauen, ob das überhaupt so relevant ist.
Natürlich ist das relevant. Das sieht man bei jedem etwas größeren Projekt

> Wenn der code dann wirklich schrecklich aussieht, kann man das ja immer noch einführen.
Ohne Linter wird es nicht gut gehen. Wenn man einmal angefangen hat und eine große Sauerei hat, wird es viel zu anstengend sein das alles wieder grade zu bügeln.

> Weil es wäre jetzt erstmal Arbeit, die nicht hilft mit dem Spiel anzufangen.
Es wäre jetzt weniger Arbeit als später.

> Es ist zudem sehr schwer sich auf einen einheitlichen Code style zu einigen, weil jeder einen anderen Code style hat.
Es ist ganz einfach. Man nimmt einfach existierende Richtlinien und Tools

**Comment by RedstoneMedia** [comment]
Ist das hier ein größeres Projekt? Ich glaube nicht. \
Außerdem wird der Code ja sowieso bei der Abstimmung reviewed, da sieht man auf den ersten Blick, ob der Code style relativ in Ordnung ist.

**Comment by Joshix-1** [comment]
> Ist das hier ein größeres Projekt? 
Das wird ein Spiel. Da braucht man schon mal schneller mehrere Dateien und hunderte Zeilen von Code. Ohne Linter wird as nichts.
> Außerdem wird der Code ja sowieso bei der Abstimmung reviewed
Wozu manuell machen, wenn es auch einfach automatisch geht?

**Comment by RedstoneMedia** [comment]
Wenn du meinst 🙂.

**Comment by ckanitz** [comment]
> Ist das hier ein größeres Projekt? Ich glaube nicht. Außerdem wird der Code ja sowieso bei der Abstimmung reviewed, da sieht man auf den ersten Blick, ob der Code style relativ in Ordnung ist.

allein daran denken müssen ist eine Aufgabe extra. Linter sind dafür da, damit das eben nicht mehr gemacht werden muss und so strikt sind die GDScript Style rules jetzt nicht. Zumal man sich mit der Zeit eh daran gewöhnt und den code automatisch direkt richtig formatiert

**Comment by RedstoneMedia** [comment]
Ich find ja prinzipiell nen einheitlichen Code style auch nicht schlecht, aber ich persönlich hab da noch nie so einen großen nutzen draus gezogen. Manche Regeln nerven mich Persönlich einfach (z. B. Komma am Ende von Enum Variants, Code Reihenfolge) und führen zu mehr Arbeit, bei den Developern, ohne großen Mehrwert. Wenn es jetzt um Sachen wie Namensgebung gibt bin ich voll dabei, aber die kann man nur bedingt automatisch Linten. \
Also: Wenn wir wirklich nen Linter nehmen, nehmt bitte nicht die Standardeinstellungen 🙏.

**Comment by ckanitz** [comment]
>  ohne großen Mehrwert

Das kann ich so nicht unterschreiben. Der Mehrwert in **einheitlichen** Regeln ergibt sich schon aus dem Wortsinn. Lesbarkeit ist erhöht, bisher Unbeteiligte können sich besser einarbeiten, der Code ist mehr "predictable").
Der von dir erwähnte Mehraufwand beschränkt sich auf den Bruchteil der Gesamtentwicklungszeit und daher imho absolut zu vernachlässigen.

**Comment by RedstoneMedia** [comment]
Ich mein nicht den Mehrwert von einheitlichen Regeln als Konzept, sondern den Mehrwert von sehr spezifischen einzelnen konkreten Regeln. Ich glaube da gibt es ein Missverständnis.

**Comment by Numenter** [comment]
Einheitlichen Code Style hört sich gut an.
Mir stellt sich die Frage, wie sich so ein Tool auf die Anfängerfreundlichkeit auswirkt.
Ist es Serverseitig und oder muss man sich was Installieren? Wie strikt sind die Regeln?

**Comment by BlobCodes** [comment]
> Einheitlichen Code Style hört sich gut an. Mir stellt sich die Frage, wie sich so ein Tool auf die Anfängerfreundlichkeit auswirkt. Ist es Serverseitig und oder muss man sich was Installieren? Wie strikt sind die Regeln?

Man müsste sich dann die oben verlinkten tools lokal installieren. Die Regeln sind nicht besonders strikt, sind eher paar basics.

**Comment by Joshix-1** [comment]
Man könnte aber machen, dass eine Github-Action einem automatisch sagt, wenn etwas falsch ist. Selbst automatisches Korrigieren durch die Action sollte möglich sein

**Comment by BlobCodes** [comment]
> Man könnte aber machen, dass eine Github-Action einem automatisch sagt, wenn etwas falsch ist. Selbst automatisches Korrigieren durch die Action sollte möglich sein

Dass eine GH-Action meckert wenn der Style nicht eingehalten wird, war ja von Anfang an im Gespräch. Den Code aber durch eine Action selbst zu formatieren klingt wie eine schlechte Idee.

**Comment by BjoernAkAManf** [comment]
Ich würde eher vorschlagen eine

**Comment by BjoernAkAManf** [comment]
Ich würde eher Vorschlagen dies ins Tooling zu integrieren. Beispielsweise mit Earthly (Siehe #14 ). Ist zwar mehr als "nur" Godot und "Git" aber finde ich besser, weil wir so alles mit einem Befehl automatisieren können. Eine Anleitung ist ja einfach gemacht.

**Comment by BlobCodes** [comment]
> Ich würde eher Vorschlagen dies ins Tooling zu integrieren. Beispielsweise mit Earthly (Siehe #14 ). Ist zwar mehr als "nur" Godot und "Git" aber finde ich besser, weil wir so alles mit einem Befehl automatisieren können. Eine Anleitung ist ja einfach gemacht.

Du möchtest ja soweit ich das sehe das gesamte CI in Earthly umsetzen (nie gehört, kann nix dazu sagen, klingt aber nach overhead). Den Linter könnte man natürlich dann auch darin umsetzen.

Aber ein Formatter hat im CI nichts verloren.

**Comment by Joshix-1** [comment]
> Aber ein Formatter hat im CI nichts verloren.
Warum nicht? Man kann doch einen eigenen Workflow dafür machen. Der kann dann einen Commit mit den Fixes erstellen und Pushen.

**Comment by BjoernAkAManf** [comment]
> Du möchtest ja soweit ich das sehe das gesamte CI in Earthly umsetzen (nie gehört, kann nix dazu sagen, klingt aber nach overhead). Den Linter könnte man natürlich dann auch darin umsetzen.

Ich würde da nicht von Overhead reden. Ist für mich eine reine Architektur Entscheidung.
Kann natürlich auch alles darüber laufen, bin aber nicht zufrieden gewesen mit den Lokalen Github Actions Emulatoren wo ich diese zuletzt ausprobiert habe. Zwei Dateien pflegen als alternative (und wenn es die Readme.md wäre) wäre dahingegen ein größerer Overhead.

Makefiles würden natürlich auch gehen 😄 .
 
> Aber ein Formatter hat im CI nichts verloren.

Wenn das nur im Pull Request läuft, wäre das okay, würde das nicht auf den Main Branch packen. Setzt dann aber afaik auch vorraus, dass das editieren durch Maintainer erlaubt wird durch den original Author. Autofixes sind hilfreich, weil diese den Aufwand reduzieren für einen neuen contributor.

**Comment by BlobCodes** [comment]
> > Aber ein Formatter hat im CI nichts verloren.
>
> Warum nicht? Man kann doch einen eigenen Workflow dafür machen. Der kann dann einen Commit mit den Fixes erstellen und Pushen.

1. Bei CI geht es um Verschnellerung von Produktzyklen und Code-Feedback. Das Formatten hat definitorisch erstmal nichts mit CI zu tun
2. Was passiert, wenn ich schnell zwei commits nacheinander ins git pushe? Der formatter der ersten CI Pipeline würde in dem Fall nicht committen können.
3. Wenn ich einen commit ins git pushe und mir plötzlich ein kleiner typo oder sonstiges auffällt muss ich warten bis die CI Pipeline endlich fertig ist oder commiten, pullen und mergen.
4. Das ganze hat einen großen Konfigurationsaufwand. Dass die action in alle pull requests reinpushen kann, ist schon aufwand genug, aber lokal ist das nochmal was ganz anderes.

**Comment by Joshix-1** [comment]
Wegen 4.: Stimmt Auto-Formatting ergibt nur Sinn, wenn man direkt auf main pusht.

2. & 3. stimmt aber so mit Github Actions nicht. Wenn du zwei Commits direkt hintereinander Pushst wird einfach der erste Run abgebrochen und der 2. fixt das dann für beide Commits.

Github-Action für einfache Auto-Commits:  https://github.com/marketplace/actions/git-auto-commit

**Comment by ckanitz** [comment]
added by https://github.com/letsgamedev/Suffragium/pull/16

Thanks @Joshix-1
