### ISSUE TITLE
[Brainstorming] Spielidee

### ISSUE THREAD

**Issue by ckanitz** [letsgamedev/Suffragium#12]
Wie [hier](https://github.com/letsgamedev/Suffragium/issues/3#issuecomment-1137412009) bereits angemerkt bräuchte es generell eine Idee, wo das Spiel überhaupt grob hingehen soll. Also her mit euren Ideen.

Tipps für den Pitch:
- KISS - Keep it Short and Simple. Im besten Fall knackig in wenigen Sätzen die Kernidee formulieren
- realistisch bleiben - Das hier wird recht sicher nicht das nächste GTA oder WoW
- zeige evtl. Beispiele - Gibt es schon Spiele / Filme / Kuchen die ähnlich zu deiner Idee sind?

**Comment by RedstoneMedia** [comment]
Wie wärs mit nem 2D Side Scrolling Platformer, hat bestimmt noch niemand gemacht.

**Comment by ckanitz** [comment]
Beim Thema "Wasser" bei einer der früheren Community Challenges hatte ich folgende Spielidee:

- Artstyle: Angelehnt an Paper Mario -> 3D Environment, Handgezeichnter 2D-Player
- Setting: Post-Apokalyptisch / "Wasserkriege" á la Mad Max

Der Spieler befindet sich in einer Art Wüstenwelt. Dabei trägt er einen Wassertank + Werfer welcher modifizierbar ist um bspw. einen Enterhaken dranzubasteln. Gegner wären "ausgetrocknete" Tiere die aufgrund ihrer Dehydrierung bösartig sind und müssen mit Wasser "abgeschossen" werden um wieder normal zu werden. Ebenfalls sollte sich der Boden (oder bestimmte Bodenregionen) wieder mit Rasen und Blumen füllen, sollte Wasser darauf kommen. Dazu Ruinen zum Erkunden - nicht unbedingt mit Dungeon Charakter.

**Comment by ASecondGuy** [comment]
Ich fände es cool wenn sich das game in jedem Level ein bisschen verändert.
Zum beispiel wie in Mario games jede Welt eigene Features hat.
Da könnte man auch von 2d platformer auf 3d wechseln.
Im Extremfall wäre das ne minigame sammlung a la Warioware.

**Comment by Joshix-1** [comment]
Eine Sammlung von Spielen find ich eine gute Idee. Das würde vieles erleichtern.

Man könnte vielleicht ein Party-Spiel wie Super Tux Party ( https://supertux.party/ ) machen

**Comment by MarioLiebisch** [comment]
Finde die Idee mit "viele kleine Spiele" gar nicht mal so verkehrt. Man könnte ein einfaches "Framework" aufsetzen, in das sich einzelne Minispiele als Szene laden lassen und dann vielleicht doch einfach mal einfach nur als Wario-Ware-Klon? Das ermöglicht sehr vielen für sich bzw. eigenständig an ihren Ideen zu arbeiten und die auch einzubringen. Unterschätzt sonst nicht mögliche Konflikte usw., wobei man Neulinge sonst sehr, sehr schnell auch abhängt bei Git.

**Comment by RedstoneMedia** [comment]
Finde die Idee von vielen mini Spielen auch gar nicht so schelcht. Ich wäre aber trotzdem für ein Main game, bei dem die Progression von dem Verhalten in den mini Spielen abhängig ist. Dann könnte man z.B trotzdem noch eine übergreifende Story und übergreifende Progression einfügen.

**Comment by ASecondGuy** [comment]
Ich hab mal sowas mit minispielen schonmal gemacht. Das werd ich morgen früh mal modernisieren und ein pull request machen. Wenn das genug Leute gut finden haben wir immerhin schonmal einen Anfang. Ein Mario party oder ähnliches sollte sich da gut drauf bauen lassen.

**Comment by RedstoneMedia** [comment]
Ich weiß nicht, ob es eine gute Idee ist etwas Altes zu Umfunktionieren. Das ist ja eher weniger demokratisch. Wir sind uns ja jetzt noch nicht 100 prozentig einig, ob das mit den Minispielen eine gute Idee ist. Was genau hast du denn da schon gemacht? Mehrere Minispiele, oder nur das Framework?

**Comment by RedstoneMedia** [comment]
Die Frage ist jetzt: wollen wird das wie Mario Party zu nem Multiplayer game machen ? Also das muss nicht unbedingt online sein, halt local multiplayer.

**Comment by ASecondGuy** [comment]
Wenn es ein richtiges Partygame werden soll braucht es auf jeden Fall MP. Du kannst alleine keine gute Party feiern.
Minispielsammlung mit spielübergreifenden Elementen wäre dann schon eher was für SP.

**Comment by techel** [comment]
Mario Party-artig find ich gut. Dann gibt es nicht nur ein paar Minispiele, sondern auch eine Overworld.

**Comment by Numenter** [comment]
Ein Einzelspieler/Coop Erlebnis, in den man versucht (im Suffragium Thema) seine Stimme abzugeben.
Das Spiel ist in verschiedenen Genes aufgeteilt, die jeweils aus mehreren Leveln bestehen. In den das Hauptziel ist, seinen Stimmzettel zur Wahlurne zu bringen.
Nebenziele könnten Zeit, Collectables oder Geheime Minigames sein.

Es Sollte eine begrenzte Anzahl aus Genes sein, damit es nicht zu unübersichtlich wird.
ein paar Beispiele:
- 3d rennspiel allar Macio Kart
- pixel sidescroller
- topdown rpg

Mit 4-5 Genes mit jeweils 5 Levels, haben wir dann n rießen Scope in den für jeden etwas dabei sein sollte. Etwas 3D, etwas Pixel und Multiplayer/Splittscreen.
Wenn das zu viel ist kann man ja die Genes reduzieren.

**Comment by sera619** [comment]
Moin Moin!
Ich bin ein RPG Freund daher geht meine Idee dann eher in diese Richtung. Ich selbst bevorzuge 2D weil ich mit 3D kaum bis keine Erfahrung habe. Aber die eigentliche Idee besteht darin uns alle selbst mit etwas Überspitzten Charactereigenschaften ins Spiel zu bauen. Vielleicht sogar als Gruppe von 3 -6 Leuten die man im Dungeon Siege 1 + 2 Style steuert.
Man kann dafür dann auch gerne eine moderneres Setting nehmen. SO ein bisschen wie in den neueren South Park Teilen. 

Ich denke das  so ein Multiversum sich ganz nett anhört sich doch aber dann schnell sehr sehr aufblähen kann. Und man den Walkd vor lauter Bäumen nicht mehr sieht. Ich denke am Anfang sollten wir uns doch eher erstmal in eine Richtung bewegen. Vielleicht auch erstmal nur so ein kleines TestDinges machen um uns mal kennen zu lernen. Stärken und Schwächen zu der Gruppe zu erkennen und unsere persönlichkeiten ^^ Vielleicht haben wir ja alle so ein gemeinsames "Ding" =D 

Anyway Mag auch sein das ich persönlcih die Mario Party Spiele nicht sonderlich mochte aber mal schauen.

**Comment by ckanitz** [comment]
With this PR https://github.com/letsgamedev/Suffragium/pull/15 we could close this for now for a "done is better than perfect" approach and getting productive.

After the merge maybe someone could streamline the game loading but the possibility to have "subfolders" to add any game and a simple selection main menu everyone is able to develop in their own sandbox.

As mentioned in the Readme:
> Everyone can participate in this project. Just open a pull request with a feature you'd like to be added. Maybe your PR gets merged, or maybe not. The community decides.

Let's just do this. If someone commits a game the majority likes it's added. If someone likes a game and wants to contribute to that, that's fine as well.

Maybe after we got some "sandboxed" games we'll have one to work on as a main game and maybe keep the other ones to implement at some place in the main. Or we'll keep it a collection, which is fine as well.

Add a 👍 or 👎 to this comment. Depending on the upvotes (excluding myself) I'll consider this proposal as excepted and will close the issue tomorrow 21:00 (9pm) CEST.

//edit
tomorrow that'll be 31st May, just to clear that out
