### ISSUE TITLE
[Abstimmung] Zurück auf Anfang: Welche Sprache überhaupt?

### ISSUE THREAD

**Issue by MarioLiebisch** [letsgamedev/Suffragium#18]
Ich fand es ja irgendwie schon interessant, wie hier gleich erstmal alle möglichen Sachen diskutiert werden, aber irgendwie ein Sprachenmischmasch herrscht anstatt das erst mal zu klären:

Aktuell sind ja einige Issues ganz Deutsch, andere haben englischen Titel mit deutschem Text darunter… Kraut und Rüben?

**Sollten Commits, Pull Requests, usw. (von Deutschsprachigen) denn nun in Englisch oder Deutsch verfasst sein?**

*Damit keine Tendenzen durch die Emoji-Wahl aufkommen schreib ich hier gleich zwei Antworten. Reagiert einfach beliebig auf die Option, der ihr zustimmt.*

**Comment by MarioLiebisch** [comment]
🇩🇪 Titel und Text sollten auf Deutsch verfasst sein, außer man beherrscht die Sprache einfach nicht.

**Comment by MarioLiebisch** [comment]
🇬🇧 Titel und Text sollten immer auf Englisch verfasst sein, außer man beherrscht die Sprache einfach nicht.

**Comment by Numenter** [comment]
Wollen wir das Suffragium ein Globales Projekt wird, oder soll es “nur” ein Lokales Projekt bleiben?
Wenn es erstmal im Lokalen/Deutschen Raum stattfindet. Sehe ich keinen Grund die Issues in Englisch zu schreiben.
Kommentare im Code hingegen können in Englisch sein. Damit ein Wechsel ins Englische schneller umzusetzen ist. Code Sollte meiner Meinung nach eh in Englisch sein.

**Comment by BjoernAkAManf** [comment]
Auch der deutsche Raum ist sprachlich vielfältiger als "nur" deutsch. Wenn es ein spiel wird, das man auch spielen kann, sollte das spiel auch lokalisierbar werden. Wenn dies der fall ist, sollte auch jeder die Möglichkeit haben im Entwicklungsprozess teilzuhaben . Daher ist englisch mMn. Pflicht.

**Comment by RedstoneMedia** [comment]
Ich finde, man soll einfach die Sprache nehmen, die man am besten kann. Dann kann man sich besser ausdrücken und es kommt vielleicht nicht so oft zu Missverständnissen. Das kann schonmal passieren, wenn man nicht in seiner Muttersprache arbeitet.

**Comment by Numenter** [comment]
Missverständnisse kommen auch unter Muttersprachlern vor.
Wenn jetzt einer Spanisch oder Französisch schreibt, weil er sich so besser ausdrücken kann verstehen wir (außer einer kann die Sprache :P) ja auch nicht.

BjoernAkAManf hat gute Argumente geliefert, warum wir schon der Zugänglichkeit halber, English bevorzugen sollten.

**Comment by RedstoneMedia** [comment]
Gut das war jetzt aber auch nur auf Englisch und Deutsch bezogen. Spanisch und Französisch stehen ja noch nicht mal zur Auswahl. Und das BjoernAkAManf jetzt gute Argumente geliefert hat, ist immer noch deine Meinung.

**Comment by Numenter** [comment]
Richtig. Es geht nicht um Spanisch oder Französisch. Zumindest nicht direkt. **Glaube Ich**.
**Meiner meinung nach**, geht es um Zugänglichkeit/Inklusivität für Anderessprachler. Niemand will hier irgendjemanden dazu zwingen in Englisch zu schreiben, **davon bin ich überzeugt**. :P

Aber jetzt mal im Ernst. Es geht doch um die Anderessprachler, oder nicht? Zumindest lese ich das so.
Deshalb ging es in meinem ersten Beitrag ja um Global vs Lokal.
Wenn es um mich persönlich ginge, würde ich Deutsch und alles im Code in Englisch wählen.
Aber wenn man die Reichweite betrachtet, ist der deutschsprachige Bereich, ein kleines Tümpelchen. (Alles meine Meinung. Also, Finger weg!)

**Comment by sera619** [comment]
Also Grundlegend Englisch würde ich sagen bei allem was offiziell eingesehen werden kann. Um eben keinen zu behindern. Wie man das Intern hält is glaub ich Lachs wie Aal.  Es sei denn eben wir behalten uns vor einfach im deutschen Sprachraum  zu bleiben dann würde ich aber tatsächlich auch deutsch bevorzugen =D

**Comment by ckanitz** [comment]
As by now, 30th May, 21:00 CEST, after four days the vote is clearly in favor of english.

@MarioLiebisch Please add a note to the readme via a new PR and close this issue afterwards.

**Comment by RedstoneMedia** [comment]
Ah, yes 63% pro English very clear. That's not a Supermajority, but fine, call it "clearly".

**Comment by ckanitz** [comment]
It's a big portion over 50% and votes are collected for four days now. We could argue about chosen words but in my opionion it's set. We can't let have votes open forever. They'll be useless this way.
