### ISSUE TITLE
Wie wäre es mit 3D ?

### ISSUE THREAD

**Issue by ahoyuri** [letsgamedev/Suffragium#3]
Godot wird, so habe ich das Gefühl, für seine 3D fähigkeiten eher belächelt.
Aber vielleicht könnte das ja ein Ziel sein. Anderen zu zeigen wie schön Godot auch in 3D sein kann.

**Comment by techel** [comment]
Spindle 3D

**Comment by AnderWoche** [comment]
Ich würde eher 2D bevorzugen weil wenn wir 3D machen, müssen wir sicherstellen das es auch ausreichend Leute in der Community gibt, die auch die Entsprechenden modele anfertigen. Bei einem 2D game ist es einfacher auch für nicht "Grafiker" schöne Texturen hinzubekommen.

**Comment by dzatoah** [comment]
Democratic Doom? :D

**Comment by AnderWoche** [comment]
Ich währe für mehr Family-friendly.

**Comment by ahoyuri** [comment]
Wir könnten das spiel so rendern wie das erste Doom. Aber irgendwas freundlicheres reinsetzten in die Spiele welt.

**Comment by dzatoah** [comment]
Family-Friendly Democratic Doom. Nein Spaß :D

Fände ich cool. Aber das rendering sollte nicht das "haupt-feature" werden...

**Comment by ckanitz** [comment]
Für möglichst viel Inklusion in der Entwicklung würde ich eine Mischform vorschlagen. So können sich sowohl 3D als auch 2D-Artists einbringen. Man müsste sich im Vorfeld dann eben etwas mehr Gedanken zur Stilrichtung machen.

Zwei Beispiele, die 3D und 2D mixen:

- Ragnarok Online (3D environment, 2D objects (player, npcs, monsters))
![image](https://user-images.githubusercontent.com/9444820/170227767-8fee3e8f-da37-478a-8548-70863545725b.png)

- Paper Mario
![image](https://user-images.githubusercontent.com/9444820/170227876-6cf04c4f-7e50-49f7-997c-6e514478be68.png)

**Comment by VatrasCell** [comment]
Wenn wir genug Leute habe, die 3D Modelle und Animationen erstellen können, hab ich nichts gegen 3D. Da ich aber fast die Befürchtung habe, dass hier am Ende fast nur Programmierer sind... :D

**Comment by Tetrakishexaeder** [comment]
> Wenn wir genug Leute habe, die 3D Modelle und Animationen erstellen können, hab ich nichts gegen 3D. Da ich aber fast die Befürchtung habe, dass hier am Ende fast nur Programmierer sind... :D

Ich kann ganz gut mit Blender umgehen bin aber noch kein Profi.

**Comment by techel** [comment]
3D und 2D lassen sich auch zu sowas wie Octopath Traveler oder das was Tom mal präsentiert hat mischen

**Comment by dzatoah** [comment]
Paper Mario Style <3

**Comment by RedstoneMedia** [comment]
Man könnte auch ein 2D Game machen, was Texturen verwendet die z. B. in Blender gerendert wurden. Dann kann man z. B. Animationen und Rotationen von Texturen deutlich einfach herstellen.

**Comment by ckanitz** [comment]
> Man könnte auch ein 2D Game machen, was Texturen verwendet die z. B. in Blender gerendert wurden. Dann kann man z. B. Animationen und Rotationen von Texturen deutlich einfach herstellen.

quasi wie beim SNES Donkey Kong Country?

**Comment by RedstoneMedia** [comment]
Kenn mich jetzt nicht mit dem Game aus, aber Factorio macht das z. B. auch.

**Comment by ASecondGuy** [comment]
Wäre es nicht sinnvoller zu bestimmen was es für ein game wird und dann zu kucken ob 2D oder 3D besser ist?
Erst einen Artstyle bestimmen und dann ein game drum rum bauen kann nach hinten los gehen.

**Comment by RedstoneMedia** [comment]
Ich gebe dir Prinzipiell recht, dass eine Spielidee erstmal das wichtigste ist, aber manche Games eignen sich halt besser in 2D oder 3D.\
Versuch mal nen FPS-Shooter in 2D zu machen.

**Comment by ckanitz** [comment]
kinda turned out as a duplicate. See https://github.com/letsgamedev/Suffragium/issues/12#issuecomment-1141416109 for the latest update.

@ahoyuri maybe consider to close this issue?

**Comment by Numenter** [comment]
@letsgamedev, I thing this can be closed.
