### ISSUE TITLE
Grafischer Stil

### ISSUE THREAD

**Issue by chlyNiklas** [letsgamedev/Suffragium#36]
Ich denke, Suffragium braucht einen einheitlichen Stil z.b. Pixelart mit vordefinierter Pixelgröße und Farbpalette.

**Comment by ASecondGuy** [comment]
Ich bezweifel dass das klappen wird.
Das beste was wir hinkriegen ist glaub res://shared/ mit Zeug zu füllen das dann von möglichst vielen benutzt wird.

**Comment by RedstoneMedia** [comment]
Wir haben jetzt schon zu wenig Grafiker, wenn wir jetzt noch mehr verjagen wird das nichts. Ich als Programmierer kann eigentlich nur einen Artstyle, alles, was davon abweicht, kriege ich nur erschwert hin und ich denke, das geht auch anderen so.

**Comment by Antricks** [comment]
Wäre es denkbar, einen Baukasten an grundlegenden GUI-Bausteinen zur Verfügung zu stellen, sodass man zumindest oberflächlich einheitlich bleibt?

**Comment by ASecondGuy** [comment]
Timer oder so würde Sinn machen aber für das Restliche UI würde ich ein Theme vorziehen.
Timer wäre aber vielleicht im GameManager besser aufgehoben?

**Comment by b7g** [comment]
siehe #45

**Comment by Numenter** [comment]
You want to make some pixel art? "Pixel Side Scroller" needs a complete makeover. Its basically a blank canvas.
