### ISSUE TITLE
Branch protection rules

### ISSUE THREAD

**Issue by Numenter** [letsgamedev/Suffragium#44]
We should add [Branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches), to prevent future faulty PR merges!

You find the Branch protection rules under Repo > Settings > Branches > Add rule.
![image](https://user-images.githubusercontent.com/84922125/173884210-fe919016-e69f-47a4-99d6-5faa4f558183.png)

Which rules should be added?
---

- [x] Require a pull request before merging
  - [x] Require approvals
  - Required number of approvals before merging: 2
  - [x] Dismiss stale pull request approvals when new commits are pushed
  - [ ] Require review from Code Owners
- [x] Require status checks to pass before merging
  - [ ] Require branches to be up to date before merging
- [x] Require conversation resolution before merging
- [ ] Require signed commits
- [ ] Require linear history
- [ ] Require deployments to succeed before merging
- [x] Include administrators

**Comment by Numenter** [comment]
I thing, those rules are nice to have.
- Require a pull request before merging
Require approvals = 2
Dismiss stale pull request approvals when new commits are pushed
- Require conversation resolution before merging
- Include administrators

**Comment by BjoernAkAManf** [comment]
Maybe require approvals from previous contributors rather than admins. Also need to update guidelines simuntaneously. Could be helpful to have something like #20 where we keep track of those decisions.

in any case we should not say maybe to rules, but rather say we want those rules. If one disagrees, we can talk about that in particular (e.g.  with the critique i said above)

**Comment by Numenter** [comment]
> Maybe require approvals from previous contributors rather than admins

Where does it say this. I don't see it.

I will change the issue structure.

**Comment by BjoernAkAManf** [comment]
Im refering to include admins. I dont believe thats nwcessary but rathee we need the approval of atleast one contributor.

Github has no settings for that though as far as i know.

**Comment by Numenter** [comment]
"Include administrators" is the most important rule form all of them. We are trying to protect for faulty PR merges.
Who does the merges for us? The all mighty administrator.
![image](https://user-images.githubusercontent.com/84922125/174096105-05c85b38-a14c-4e8d-a7db-7b0ecce1c138.png)

Require a pull request before merging just require a approval. It don't have to be someone with rights, right?
