### ISSUE TITLE
Auswahl einer Licence

### ISSUE THREAD

**Issue by ckanitz** [letsgamedev/Suffragium#5]
Bleiben wir bei MIT? Evtl. GPLv2? Vorschläge plis!

(Nach Anmerkung von DipDill im Discord)

**Comment by TazorDE** [comment]
[WTFPL](https://de.wikipedia.org/wiki/WTFPL)?

**Comment by dzatoah** [comment]
Neee, Tom meinte doch irgendwo im Video "Keine kommerzielle Nutzung." GPLv2 ist auch mein Standard. Aber keine Ahnung wie kommerzielle Nutzung da geregelt ist.

**Comment by techel** [comment]
Da unter anderem keine kommerzielle Nutzung, fallen GPLv2 und WTFPL schon weg. Einfach das, was Tom sagte, in einer Datei zusammenfassen und fertig.

**Comment by dzatoah** [comment]
Vorallem sollten wir das jetzt klären und nicht später wo wir viele viele Verschiedene Code-Autoren haben. Sonst müsste man später alle die jemals was am Code beigetragen haben, fragen ob sie einverstanden sind die Lizenz zu ändern.

**Comment by Mat2095** [comment]
"Creative Commons Attribution NonCommercial" schließt (wie der Name sagt) kommerzielle Nutzung aus. Keine Ahnung ob das was wäre.
https://tldrlegal.com/license/creative-commons-attribution-noncommercial-(cc-nc)

**Comment by Joshix-1** [comment]
Für mich persönlich wäre non-commercial nicht so wichtig. Das ist finde ich auch schwierig.
Ich fänd wichtiger, dass niemand darauf aufbauend eine proprietäre Software macht. GPL/EUPL oder AGPL (wenn es Backend-Code gibt) fänd ich am besten.
Bei der EUPL wäre garantiert, dass die in Europa rechtskräftig ist.

Wenn wir die AGPL nehmen würden, dann wäre zwar eine kommerzielle Nutzung möglich, aber der Code wäre frei also könnten wir weiter davon profitieren und den Code gratis nutzen.

**Comment by RedstoneMedia** [comment]
Also ich wäre für die GNU-GPL3 die schließt schon recht viel aus, nur halt nicht den kommerziellen Aspekt, sondern nur der Offene

**Comment by BlobCodes** [comment]
> Für mich persönlich wäre non-commercial nicht so wichtig.

Sehe ich genauso, gibt auch keine großen Copyleft-Lizenzen, welche Kommerzielle Nutzung verbieten (Creative Commons ist für Code eher ungeeignet).

---

Ansonsten scheint ja wichtig zu sein, dass das ganze Copyleft ist, damit niemand den Code einfach proprietär nutzt. Die einzelnen Lizenzen unterscheiden sich jetzt nicht so sehr voneinander (egal ob GPL, EUPL, Apache, etc). Würde also auch einfach die GPLv3 in den Raum werfen, da diese viel beliebter/bekannter als EUPL und Apache ist.

**Comment by ckanitz** [comment]
WTFPL können wir also schonmal ausklammern.

Was ich sonst nun so rauslese ist:
- [GPL3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) 🎉
- [EUPL](https://tldrlegal.com/license/european-union-public-licence) 🚀
- [CC-BY-NC](https://tldrlegal.com/license/creative-commons-attribution-noncommercial-(cc-nc)) 👀
- [MIT](https://tldrlegal.com/license/mit-license) 😄

Evtl. mal auf diesen Kommentar mit dem entsprechenden Emoji reagieren und das mit den meisten Stimmen nach 24h festsetzen?

PS: Die Emojis sind komplett ohne Wertung. Sehr viel mehr stellt GH einfach nicht zur Verfügung - oder ich seh nicht wo :D

**Comment by dzatoah** [comment]
Das Ding ist, ich hab keine Ahnung was die Unterschiede sind.

**Comment by ckanitz** [comment]
Darum habe ich alle noch einmal auf tldrlegal verlinkt. Mach dir die vier mal parallel auf und flieg drüber, dann siehst du schnell die essentiellen Unterschiede

**Comment by BlobCodes** [comment]
> Das Ding ist, ich hab keine Ahnung was die Unterschiede sind.

Hier ist auch noch ein Artikel, der das ganze einfach erklärt (bis auf die CC-BY-NC, aber die ist für code eigentlich ungeeignet):
https://www.adesso.de/de/news/blog/open-source-lizenzen-und-was-ich-damit-machen-darf.jsp

**Comment by Ione15** [comment]
GPL3 macht mehr sinn da auch Forks unter GPL3 veröffentlicht werden müssen und EUPL eher unbekannt ist.

**Comment by Joshix-1** [comment]
APGL würde am meisten Sinn ergeben, wenn das Spiel auch Multiplayer-Elemente mit Backend haben soll.
Das EUPL eher unbekannt ist, find ich egal. Bei EUPL wäre garantiert, dass die in der EU rechtskräftig ist. Somit wäre die besser als GPL

**Comment by MarioLiebisch** [comment]
Der Vollständigkeit möchte ich mich nochmal selbst aus dem PR zitieren:

> Auch wenn ich allgemein kein Fan der (A/L)GPL bin (für mich sind MIT und BSD viel, viel freier als die "freie" (A)GPL-Software), würde ich für ein Projekt wie das hier allgemein und **definitiv** von der (A)GPL abraten, da das Projekt dadurch (finde ich) nichts gewinnt, gleichzeitig aber viele Fallstricke, gerade für Neulinge, mit reinkommen – es würde also nur schaden:
> 
> * Neueinsteiger, Lernende usw. haben eine Tendenz zum Kopieren. Dagegen spricht auch absolut nichts. Im Gegenteil: Ein solches Projekt lädt finde ich gerade dazu ein, etwas bestehendes zu kopieren und dann ggf. neu zu implementieren und dann evtl. auch wieder in das Original einfließen zu lassen. Gerade das ist ja auch ein wichtiges Konzept beim Lernprozess.
>   Allerdings legt man ihnen hier durch die Copyleft-Mentalität bereits Steine, Unsicherheiten und Stolperfallen in den Weg:
>   
>   * Ab wann ist es ein "Derivat"?
>   * Wann ist es nur ein übertragenes Konzept?
>   * Wann ist es Inspiration und wann ist es direkt übernommen?
>   
>   Das sind Fragen, über die sich auch alte Hasen gerne mal streiten (hierzu passt auch beispielsweise der Rechtsstreit Oracle gegen Google rund um die Java API). Ein Neuling ist davon ggf. auch noch völlig überfordert. Und es reicht hier ja nicht, einfach nur zu sagen, "mein Code ist auch GPL", da ja effektiv auch diverse Verpflichtungen ergeben.
>   MIT lässt sich eigentlich schön kurz zusammenfassen: Mach was du willst, behaupte nur nicht, du hast es geschrieben, und erwähne den Ursprung irgendwo. Bei der GPL… nun, ich denke, ich muss da nicht alles aufzählen, was man _eigentlich_ für die perfekte Konformität alles sicherstellen soll/muss usw.
> * Niemand mag sich x Seiten Lizenz durchlesen. Die MIT-Lizenz passt auf weniger als eine halbe Seite und lässt sich auch super verkürzen/zusammenfassen (wodurch natürlich einige Details leiden). Wer sich erst einmal einen halben Roman (bewusst überspitzt) durchlesen muss, nur um ggf. mitzuarbeiten, wird der gerade als Neuling nicht unbedingt tun. Je nach Herkunft, Erziehung, persönlicher Einstellung will so jemand auch nicht einfach etwas einfach so abhaken oder beiseiteschieben. Und wenn die Lizenz beiseitegeschoben wird, hat sie auch ihr Ziel verfehlt.
> * Das hier ist ein Spaß-/Freizeit-/Lernprojekt – zumindest sehe ich das als solches. Ich halte es für zweifelhaft, dass sich jemand den Aufwand und die Mühe machen würde, im Falle einer Verletzung entsprechende Schäden oder die Einhaltung der Lizenzbedingungen einzufordern oder gar einzuklagen. Und welche Schäden sollen überhaupt entstehen? Der kleine Tim, der sich für Spieleentwicklung entscheidet, hat für sein Pokemon-Fangame 2-3 Godot-Szenen aus dem Projekt genommen und sein Freizeitprojekt nicht für alle Quelloffen bereitgestellt hat, wird für 3,50€ verklagt? Bringt ihn in den Knast!
>   Einen Haftungsausschluss für die Mitwirkenden bringt auch die MIT-Lizenz bereits mit. Und wer unbedingt meint, er/sie/es müsste nun unbedingt einen komplexen Programmblock irgendwie einbringen, der unbedingt unter einer "freien" Lizenz steht, kann diese Teile doch auch als LGPL (oder auch AGPL mit einer entsprechenden Ausnahme bzgl. dem Copyleft bei der unveränderten Nutzung) veröffentlichen und das dann über einen PR einbinden.

**Comment by MarioLiebisch** [comment]
Zur AGPL-Thematik würde ich zudem noch diesen doch recht [überzeugenden Blogbeitrag](https://deavid.wordpress.com/2020/08/02/affero-gpl-is-toxic-avoid-it-like-the-plague/) (englisch) empfehlen.

Um einen wichtigen Ausschnitt zu zitieren:
> First and foremost, AGPL talks about source code but it doesn’t care about interoperability or users ability to dump their own data in an easy way. So, if even the SaaS product was AGPL compliant, they could remove or complicate the ways the user can export. By doing this, they ensure you have it really rough in order to move away from the provider. Yes, you can run the software in your premises if you know how to, but with no data, this is useless.
>
> AGPL also cannot target ill-manned modifications of the source code that make the software almost impossible to install in a compatible/usable way, while making the tool totally incompatible with upstream. Good luck there.
>
> AGPL is not used in almost any SaaS, probably not even GPL for big products. The reason is, SaaS is **very** profitable. Companies can afford making the product from scratch and will outpace quickly any open source alternative while still having huge margins.

Und viele dieser Punkte treffen finde ich auch auf die reguläre GPL zu. Wenn ihr unbedingt (A)GPL nutzen wollt, lasst euch nicht aufhalten, ich sehe nur eben nicht, wie ihr damit das erreicht, was ihr erreichen wollt. Da wäre es dann schon durchaus einfacher, z.B. die MIT zu nehmen und sie so abzuändern, dass eine kommerzielle Nutzung wesentlicher Codebestandteile schlichtweg ausgeschlossen ist.

**Comment by Joshix-1** [comment]
Wie kann man die MIT denn so abändern? Das wäre vermutlich kompliziert und dafür bräuchten wir Anwälte, um das durchsetzbar abzuändern.

Böse Leute kann man nie stoppen.

Mit der AGPL würden wir es ihnen so schwer wie einfach möglich machen.

**Comment by BjoernAkAManf** [comment]
Die MIT ist die schlechteste Wahl.

Wenn man das will muss man eben eine nicht-open-source lizenz verwenden.

**Comment by ckanitz** [comment]
see https://github.com/letsgamedev/Suffragium/pull/17
