### ISSUE TITLE
Dokumentation von Entscheidungen

### ISSUE THREAD

**Issue by VatrasCell** [letsgamedev/Suffragium#6]
Da wir hier mit einigen zusammen arbeiten und demokratisch Entscheidungen treffen wollen, ist es besonders wichtig dies transparent zu machen und die getroffenen Entscheidungen zu dokumentieren.

Mein Vorschlag hierfür wäre, dass man Abstimmungen zu einen Thema in einem separatem Issue bespricht und über die Emots als Umfrage abstimmen lässt. Eine Umfrage hat dann eine festgelegte Laufzeit (z.B. 12h, 24h etc.). Am Ende wird das Ergebnis dokumentiert. Hierfür würde ich die Wiki Funktion von GitHub bevorzugen. Das alles in der README zu machen, könnte die README etwas zu sehr aufblähen. 

Bereits getroffene Entscheidungen würde ich dann mit diesem System noch mal bestätigen lassen (z.B. welche Sprache verwendet werden soll).

Was haltet ihr davon?

**Comment by VatrasCell** [comment]
Hier mal kurz durchgespielt, wie ich mir das vorstelle:

1. Diskussions Issue erstellen
![image](https://user-images.githubusercontent.com/23477251/170257983-f778e4ea-86e6-4476-a1ab-2beb0ad82b92.png)
Am besten auch mit **[Diskussion]** kennzeichnen, um den Überblick zu behalten, wenn wir mal ein paar mehr Issues parallel haben sollten.

2. Vorschläge sammeln

3. Wenn genug zusammen getragen wurde eine Abstimmung als Kommentar erstellen.
![image](https://user-images.githubusercontent.com/23477251/170258688-17cfc9e9-e1b7-4147-9606-c45e543b8ddb.png)
Am besten dann das **[Diskussion]** zu **[Abstimmung]** ändern, um auf die Abstimmung aufmerksam zu machen.

4. Nach Ablauf der Zeit das Ergebnis dokumentieren z.B. als Kommentar mit Screenshot und das Ergebnis im Wiki dokumentieren. Den Link zur Wiki Seite dann auch ins Issue packen.

5. Issue kann geschlossen werden.

Für die ganze Diskussion und Abstimmung sehe ich den Issue Ersteller in der Verantwortung. Es können aber auch natürlich mehrere Leute ein Thema bearbeiten und zur Abstimmung stellen.

PS: Natürlich ganz wichtig: keine Entscheidung ist unumstößlich. Sollte man sich in der Masse dazu entscheiden, etwas anders machen zu wollen, ist das natürlich möglich. Das sollte dann aber, wie alles, gut dokumentiert werden. Man muss aber bedenken: es gibt Sachen, die kann man später nur noch schwer wieder ändern.

Sollte das so für euch fein sein, würde ich das heute Abend zur Abstimmung einstellen.

**Comment by VatrasCell** [comment]
Okay, ich sehe gerade, das Wiki muss wohl @letsgamedev anlegen, damit wir es nutzen können. Ich kenne mich da leider nicht gut genug mit aus. Auf Arbeit nutzen wir andere Tools 😅. Sollte das mit dem Wiki nicht funktionieren oder zu aufwendig sein, müssen wir uns noch eine andere Variante/ Plattform überlegen, wo wir Entscheidungen dokumentieren können. Nur in den Issues wird zu unübersichtlich mMn.

**Comment by ckanitz** [comment]
Generell ist git(hub) extra darauf ausgelegt, dass man so etwas schnell nachvollziehen kann, daher sehe ich gerade die Notwendigkeit nicht unbedingt, wenn es nur ums protokollarische angeht.

Ansonsten, wie du schon selbst gemerkt hast, ist das Wiki für so etwas eher geeignet als ein "gepinntes issue". Imho sollten Issues für das genutzt werden, wofür sie gedacht sind.

**Comment by dzatoah** [comment]
Sonst kann man als Wiki auch einfach einen Unterordner erstellen, theoretisch.

Und später wenn alles gut ist können wir Tom bitten den Unterordner in die Github Wiki Funktion einzupflegen

**Comment by VatrasCell** [comment]
Okay, ich werde das jetzt zur Abstimmung stellen.

Für die Doku würde ich erstmal doch die README vorschlagen, bis wir uns auf was anderes geeinigt haben. Einen entsprechenden Pull Request werde ich nach der Abstimmung anlegen.

PS: Das mit dem [Diskussion] und [Abstimmung] würde ich als optional betrachten sofern nichts dagegen spricht.

Also 👍 wer für meinen Vorschlag der Entscheidungsfindung und - Dokumentation ist und
👎 wer dagegen ist. Die Abstimmung läuft bis zum 26.05.2022, 20:00 Uhr

**Comment by BjoernAkAManf** [comment]
Würde perspektivisch Diskussionen und Abstimmungen in Github Diskussions 

Siehe auch https://resources.github.com/devops/process/planning/discussions/

Ansonsten würde mich vor der Abstimmung interessieren:
1. Wer definiert das Abstimmungsdatum? Welche Vorgaben gibt es dabei?
2. Fraglich ist, ob einfach jeder Github Account abstimmen kann. Wenn nein, welche Kriterien werden benötigt?
3. Wie versionisieren wir solche Entscheidungen? Scope kann sich häufig ändern. Das sollte entsprechend ähnlich wie ADR ( https://adr.github.io/ ) Dokumentiert werden.

Beim Zählen der Stimmen sollte dann auch entsprechend der Initiale Post ausschlaggebend sein. Den weiter unten zu Platzieren halte ich für nicht Zielführend.

**Comment by VatrasCell** [comment]
Da sich bis jetzt nur eine Person an der Abstimmung beteiligt hat und ich nicht denke, dass sich das noch groß in den nächsten zwei Stunden ändern wird, sehe ich das ganze mal als abgelehnt an.
