### ISSUE TITLE
Discussion: Path to fast-track critical changes?

### ISSUE THREAD

**Issue by MarioLiebisch** [letsgamedev/Suffragium#79]
As PR #63 (together with the issue fixed in PR #78 and to some lesser extent PR #77) showed, it might be a good idea to have some way to fast-track critical changes that actively and directly fix issues preventing new changes (or whole PRs) to get created or properly merged.

* Just merging them straight away sounds wrong, contradicts the core idea of this project, **and** might introduce new bugs, if something is pushed too fast.
* With current rules in place, the project could remain broken up to 72 hours **after** an actual fix has been developed, since getting the necessary upvotes might still be tricky (and even then there's the initial 24 hours deadline). Keep in mind this might be way longer if a fix isn't a 5 minute change, so imagine having something blocking for a week, then wait even longer? Sounds wrong, too.

Unfortunately I have no clear solution to this whole issue, as seldomly as it might happen overall.

**Comment by Numenter** [comment]
Suffragium merge process is slow by design and aimed at about 15 active people. Which does not have to be this way.
We could change thresholds to fit the current active community size or redo the system.
🚀 Adding a emote to bypass the time constraints is an option too.

**Comment by MarioLiebisch** [comment]
That's actually a good idea!🤔
