### ISSUE TITLE
Richtlinien zur Akzeptierung

### ISSUE THREAD

**Issue by RedstoneMedia** [letsgamedev/Suffragium#8]
Dieses Issue existiert, um darüber abzustimmen, mit welchem System, Merge requests oder anderen Veränderungen angenommen werden. Wie viele Daumen nach oben benötigt werden, um akzeptiert zu werden, wie lange gewartet werden muss, etc.

**Comment by RedstoneMedia** [comment]
Also eine Idee wäre es, mindestens 24h zu warten, damit frühere Personen, die früher Abstimmen, oder Fake Accounts keine Chance haben. Nach einem Tag wird dann auf das Verhältnis von Daumen hoch zu Daumen runter zu geschaut.

**Comment by ASecondGuy** [comment]
Es sollte ne Möglichkeit geben Schnell Sachen durch zu bekommen.
Bsp. Mit 90% likes geht es sofort durch (nach mind. 24h)
Aber dass auch mehr umstrittene Sachen rein kommen können reichen nach einer Woche auch zbsp. 60-70%

**Comment by RedstoneMedia** [comment]
Meinst du mit 90%, 90% aller Contributor? Dann bräuchten wir eine aktiv maintainte Liste von aktiven Contributors.

**Comment by chlyNiklas** [comment]
Ich denke eher, dass 90% der abstimmenden Leute gemeint sind. Wenn es 90% aller Contributor währ und nach gewisser zeit Manche das Interesse verlieren würden, würde das System nicht mehr funktionieren.

**Comment by ASecondGuy** [comment]
Gemeint war die Likes/Dislike Ratio. Mindestsatzt an Contributern kann man auch überlegen.
Aber ich würde daran eher die gesammt benötigten votes festmachen die ne Wahl braucht dass sie gültig ist.
Schnellspur wahl braucht mind. 20% wahlbeteiligung zum beispiel.

**Comment by BjoernAkAManf** [comment]
Automatisch Mergen halte ich für schwierig. Sollte durch mindestens einen Menschen überprüft werden.

**Comment by ASecondGuy** [comment]
Genau deswegen braucht es ja zusätzlich die mind. 24h Regel. Alles was weniger als nen Tag alt ist wird erstmal ignoriert.
Oder alternativ die mind. 20% der Contributer Regel.

**Comment by BlobCodes** [comment]
> Automatisch Mergen halte ich für schwierig. Sollte durch mindestens einen Menschen überprüft werden.

Wir könnten Maintainer bestimmen, welche Commits mergen (Repräsentative Demokratie ist immer noch Demokratie).

**Comment by RedstoneMedia** [comment]
> Wir könnten Maintainer bestimmen, welche Commits mergen (Repräsentative Demokratie ist immer noch Demokratie).

Das stimmt, aber es hat vor und Nachteile, bei einer repräsentativen Demokratie können schnell Minderheiten verloren gehen und die Maintainer müssten auch nach einer Zeit neugewählt werden, sonst müssen die Maintainer nur einmal den Leuten gut gefallen und dann können sie akzeptieren, was sie wollen.

Außerdem: Aufgrund von welchen Kriterien soll man hier eigentlich jemand wählen? \
Wir kennen uns ja praktisch nicht und nach dem Bauchgefühl gehen würde uns nicht weiter bringen.
Da müssten die Kandidaten schon einen Wahlkampf mit Wahlplakaten machen xD.

Der einzige Vorteil von einer repräsentativen Demokratie, ist in diesem Fall, dass sie schneller, also effizienter ist.
Das wäre nur das Problem, das der ganze Aufwand für eine Wahl und regelmäßige Neuwahlen wahrscheinlich so viel Zeit in Anspruch nimmt, das selbst dieser Geschwindigkeitsvorteil damit ausgeglichen wird.

**Comment by Numenter** [comment]
Since #32 changed the merge conditions. Are there any concerns that #44 would not handle?

**Comment by RedstoneMedia** [comment]
The only thing I could think of is, that we need some rules to combat the slowly diminishing amount of contributors and voters. Setting absolute limits on number of reviews or number of votes could be a problem in the future.
