### ISSUE TITLE
Translation Key Guidelines

### ISSUE THREAD

**Issue by ASecondGuy** [letsgamedev/Suffragium#81]
# Description
We need to standardize the translation key names and usage because it is unclear where to use existing ones, when to make new ones and how to call them when you need new ones.

**Comment by ASecondGuy** [comment]
I think game specific keys whould be like this:
T_\<gamefolder>_\<usecase>
For general keys the gamefolder is not needed.

But I'm not sure how much we should use general or game specific keys.

**Comment by Joshix-1** [comment]
I think the translation key should always contain just the full english text.

**Comment by RedstoneMedia** [comment]
> I think the translation key should always contain just the full english text.

I agree with this, but for texts that are too long (more than 30-40 chars) a key that describes the value in English should be used instead.

**Comment by ASecondGuy** [comment]
I guess that settles it then.

The translation key should contain just the full english text
except
if the text is too long (more than 30-40 chars) a key that describes the value in English should be used instead.
