### ISSUE TITLE
Snake color selection persists in menu background (bug)

### ISSUE THREAD

**Issue by RedstoneMedia** [letsgamedev/Suffragium#83]
# Description
Issue type: Bug Report

The snake color selection persists in the menu background after playing the snake game, but then going back to the menu before selecting a snake color.

## Steps to reproduce the issue

1. Play the snake game
2. Immediately open the pause menu
3. Select "Back to menu"

## Context
![image](https://user-images.githubusercontent.com/34373974/184212100-1a2de6d5-9e4e-4bff-ac5e-798caa55d80d.png)

**Comment by ASecondGuy** [comment]
That bug is pretty funny. 
That happens because the dialog is not a child of the game scene so the game manager doesn't delete it.
The easiest fix would be to save a reference to the dialog and delete it on tree exit if it still exists I think
