### ISSUE TITLE
GDNative akzeptieren?

### ISSUE THREAD

**Issue by RedstoneMedia** [letsgamedev/Suffragium#9]
Meine Frage wäre, ob GDNative in dem Projekt generell genutzt werden kann oder nicht (Also das Arbeiten mit C++/Rust/etc.).

## Contra:
- GDScript ist da deutlich Anfänger freundlich
- GDScript ist besser in Godot integriert
- GDNative fügt eventuell unnütze Komplexität hinzu (aufspalten des Codes in viele Codebasses)
- Nicht jeder kann C++/Rust etc.

## Pro:
- GDNative code ist deutlich schneller als GDScript
- GDNative ermöglicht das Benutzen von einer riesigen Menge an Bibliotheken
- Jeder kann in seiner Lieblingssprache Arbeiten → Codequalität wird höchstwahrscheinlich in der Lieblingssprache besser sein 
- Kein Ausschluss von Godot featuren

**Comment by BlobCodes** [comment]
> Jeder kann in seiner Lieblingssprache Arbeiten → Codequalität wird höchstwahrscheinlich in der Lieblingssprache besser sein

Ergo niemand versteht den gesamten Code, da dieser über mehrere Sprachen verteilt ist?
Wäre ja noch akzeptabel wenn nur eine Sprache zugelassen würde aber so würde das zu noch mehr Chaos führen als ohnehin schon.

**Comment by VatrasCell** [comment]
> > Jeder kann in seiner Lieblingssprache Arbeiten → Codequalität wird höchstwahrscheinlich in der Lieblingssprache besser sein
> 
> Ergo niemand versteht den gesamten Code, da dieser über mehrere Sprachen verteilt ist? Wäre ja noch akzeptabel wenn nur eine Sprache zugelassen würde aber so würde das zu noch mehr Chaos führen als ohnehin schon.

Sehe ich genauso. Wäre für mich eher die Frage, ob man GDScript oder EINE andere unterstützte Sprache nutzt.

**Comment by RedstoneMedia** [comment]
Mann könnte sich auch auf eine Sprache einigen. Fände ich auch valide.

**Comment by RedstoneMedia** [comment]
Aber die Frage ist dann, was nimmt man da. Ich wäre für Rust, aber ich denke mal fast jeder andere würde C++ nehmen.

**Comment by TazorDE** [comment]
Ich denke mal dass zum aktuellen Zeitpunkt GDNative keine sinnvolle Option ist. Entsprechend sollte man die Godot Vanillasprache GDScript nutzen. Da hat man eine gemeinsame Basis und zu einem späteren Zeitpunkt kann man entscheiden ob einzelne Komponenten die besonders davon profitieren in GDNative umgesetzt werden sollen.

**Comment by RedstoneMedia** [comment]
Ich glaube, dann wird die Frage erstmal auf Eis gelegt.
